/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.Cliente;
import Classes.Contrato;
import Classes.ContratoAPP;
import Classes.ContratoPJ;
import Classes.Veiculo;
import Classes.VeiculoUsado;
import DAO.ClienteDAO;
import DAO.ContratoDAO;
import DAO.VeiculoDAO;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author l_dsb
 */
public class aluguelForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form aluguelForm
     */
    public aluguelForm() {
        initComponents();
        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oie_401942oYTgxgbD.png")));
        readListaAlu();
    }
    
    public static boolean instanciaContratos = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContratos = new javax.swing.JTabbedPane();
        tabContrato = new javax.swing.JPanel();
        btnBuscarContrato = new javax.swing.JButton();
        lblCodContrato = new javax.swing.JLabel();
        txtCodContrato = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblVeiculo = new javax.swing.JLabel();
        cmbModelo = new javax.swing.JComboBox<>();
        cmbMotorizacao = new javax.swing.JComboBox<>();
        lblMotorizacao = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblContrato = new javax.swing.JLabel();
        btnSimularValor = new javax.swing.JButton();
        btnContrato = new javax.swing.JButton();
        btnAtualizarContrato = new javax.swing.JButton();
        lblValorDesconto = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        lblDias = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        btnSelecionarVei = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        lblDataFim = new javax.swing.JLabel();
        txtDataFim = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        tabRevogarContrato = new javax.swing.JPanel();
        btnBuscarRev = new javax.swing.JButton();
        lblCodRev = new javax.swing.JLabel();
        txtCodRev = new javax.swing.JTextField();
        lblNomeRev = new javax.swing.JLabel();
        txtNomeRev = new javax.swing.JTextField();
        lblCPFRev = new javax.swing.JLabel();
        txtCPFRev = new javax.swing.JTextField();
        lblKMAntigaRev = new javax.swing.JLabel();
        txtKMVelhaRev = new javax.swing.JTextField();
        txtKMNovaRev = new javax.swing.JTextField();
        lblKMNova = new javax.swing.JLabel();
        lblAvariadoRev = new javax.swing.JLabel();
        cmbAvariadoRev = new javax.swing.JComboBox<>();
        btnRevogar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPlacaRev = new javax.swing.JTextField();
        lblPlacaRev = new javax.swing.JLabel();
        tabListContratos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAtualizarLista = new javax.swing.JButton();
        btnBuscarLista = new javax.swing.JButton();
        txtBuscarLista = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Contratos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnBuscarContrato.setText("Buscar Contrato");
        btnBuscarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarContratoActionPerformed(evt);
            }
        });

        lblCodContrato.setText(" Código de Contrato:");

        txtCodContrato.setEditable(false);

        lblCPF.setText(" CPF do Cliente:");

        txtCPF.setToolTipText("Pressione \"ENTER\" para realizar a busca.");
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFKeyPressed(evt);
            }
        });

        lblNome.setText(" Nome do Cliente:");

        txtNome.setEditable(false);

        lblVeiculo.setText(" Modelo:");

        cmbModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Palio", "Sandero", "Uno", "Argo", "Onix", "Virtus", "Gol", "Fluence", "Captur" }));
        cmbModelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbModeloItemStateChanged(evt);
            }
        });

        cmbMotorizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "1.0", "1.4", "1.6", "1.8", "2.0" }));

        lblMotorizacao.setText(" Motorização:");

        txtPlaca.setEditable(false);

        lblPlaca.setText(" Placa:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Aplicativo", "Pessoa Física", "Pessoa Júridica" }));
        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });

        lblTipo.setText(" Tipo de Contrato:");

        lblContrato.setText(" Valor do Contrato:");

        btnSimularValor.setText("Simular Valores");
        btnSimularValor.setToolTipText("");
        btnSimularValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularValorActionPerformed(evt);
            }
        });

        btnContrato.setText("Concluir Contrato");
        btnContrato.setEnabled(false);
        btnContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratoActionPerformed(evt);
            }
        });

        btnAtualizarContrato.setText("Atualizar Contrato");
        btnAtualizarContrato.setEnabled(false);
        btnAtualizarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarContratoActionPerformed(evt);
            }
        });

        lblValorDesconto.setText(" Valor com Desconto:");

        txtDesconto.setEditable(false);
        txtDesconto.setToolTipText("");

        btnLimpar.setText("Limpar Campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblDias.setText(" Total de dias:");

        btnSelecionarVei.setText("Selecionar o Veículo");
        btnSelecionarVei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarVeiActionPerformed(evt);
            }
        });

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblDataFim.setText(" Data fim do Contrato:");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabContratoLayout = new javax.swing.GroupLayout(tabContrato);
        tabContrato.setLayout(tabContratoLayout);
        tabContratoLayout.setHorizontalGroup(
            tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelecionarVei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabContratoLayout.createSequentialGroup()
                        .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVeiculo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabContratoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(tabContratoLayout.createSequentialGroup()
                                        .addComponent(lblMotorizacao)
                                        .addGap(81, 81, 81))
                                    .addGroup(tabContratoLayout.createSequentialGroup()
                                        .addComponent(cmbMotorizacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)))
                                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabContratoLayout.createSequentialGroup()
                                        .addComponent(lblPlaca)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtPlaca)))
                            .addGroup(tabContratoLayout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(lblDias)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(tabContratoLayout.createSequentialGroup()
                        .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabContratoLayout.createSequentialGroup()
                                .addComponent(btnAtualizarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimularValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(tabContratoLayout.createSequentialGroup()
                        .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabContratoLayout.createSequentialGroup()
                                .addComponent(lblDataFim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabContratoLayout.createSequentialGroup()
                                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDataFim, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabContratoLayout.createSequentialGroup()
                                        .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblContrato)
                                            .addComponent(lblValorDesconto))
                                        .addGap(0, 69, Short.MAX_VALUE))
                                    .addComponent(txtDesconto, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)))
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabContratoLayout.createSequentialGroup()
                        .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabContratoLayout.createSequentialGroup()
                                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodContrato))
                                .addGap(18, 18, 18)
                                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCPF))))
                        .addGap(18, 18, 18)
                        .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabContratoLayout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDias, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        tabContratoLayout.setVerticalGroup(
            tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarContrato)
                .addGap(18, 18, 18)
                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodContrato)
                    .addComponent(lblCPF)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDias, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabContratoLayout.createSequentialGroup()
                        .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVeiculo)
                            .addComponent(lblMotorizacao)
                            .addComponent(lblPlaca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbMotorizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addComponent(btnSelecionarVei))
                .addGap(18, 18, 18)
                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tabContratoLayout.createSequentialGroup()
                        .addComponent(lblDataFim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblContrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblValorDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizarContrato)
                    .addComponent(btnSimularValor)
                    .addComponent(btnSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnContrato))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tabContratos.addTab("Realizar Contrato", tabContrato);

        btnBuscarRev.setText("Buscar Contrato");
        btnBuscarRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRevActionPerformed(evt);
            }
        });

        lblCodRev.setText(" Código do Contrato:");

        txtCodRev.setEditable(false);

        lblNomeRev.setText(" Nome:");

        txtNomeRev.setEditable(false);

        lblCPFRev.setText(" CPF ou CNPJ:");

        txtCPFRev.setEditable(false);

        lblKMAntigaRev.setText(" KM Atual:");

        txtKMVelhaRev.setEditable(false);

        lblKMNova.setText(" KM Nova:");

        lblAvariadoRev.setText(" Está avariado?");

        cmbAvariadoRev.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Sim", "Não" }));

        btnRevogar.setText("Revogar Contrato!");
        btnRevogar.setEnabled(false);
        btnRevogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevogarActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>\n<Center>Revise todas a condições com o cliente.</Center>\n<br><Center>A ação não tem retorno.</br></Center>\n<br><Center>Certifique-se que essa seja realmente a decisão do cliente.</br></Center>\n<br><Center>Não esqueça de atualizar a quilometragem do veículo.</br></Center>\n<br><Center> Verificar avarias!</br></Center>\n</html>");

        txtPlacaRev.setEditable(false);

        lblPlacaRev.setText(" Placa:");

        javax.swing.GroupLayout tabRevogarContratoLayout = new javax.swing.GroupLayout(tabRevogarContrato);
        tabRevogarContrato.setLayout(tabRevogarContratoLayout);
        tabRevogarContratoLayout.setHorizontalGroup(
            tabRevogarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRevogarContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabRevogarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarRev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNomeRev)
                    .addComponent(btnRevogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabRevogarContratoLayout.createSequentialGroup()
                        .addGroup(tabRevogarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvariadoRev)
                            .addComponent(cmbAvariadoRev, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(tabRevogarContratoLayout.createSequentialGroup()
                        .addGroup(tabRevogarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCodRev)
                            .addComponent(txtCodRev, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeRev)
                            .addComponent(lblCPFRev)
                            .addComponent(txtCPFRev)
                            .addComponent(lblKMAntigaRev)
                            .addComponent(txtKMVelhaRev, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tabRevogarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPlacaRev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txtKMNovaRev, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlacaRev, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKMNova, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        tabRevogarContratoLayout.setVerticalGroup(
            tabRevogarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRevogarContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarRev)
                .addGap(18, 18, 18)
                .addComponent(lblCodRev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNomeRev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabRevogarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFRev)
                    .addComponent(lblPlacaRev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabRevogarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPFRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlacaRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabRevogarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKMAntigaRev)
                    .addComponent(lblKMNova))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabRevogarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKMVelhaRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKMNovaRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblAvariadoRev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAvariadoRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRevogar)
                .addGap(21, 21, 21))
        );

        tabContratos.addTab("Revogar Contrato", tabRevogarContrato);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Contrato", "Placa", "CPF/CNPJ", "Fim do Contrato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnAtualizarLista.setText("Atualizar Lista");
        btnAtualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarListaActionPerformed(evt);
            }
        });

        btnBuscarLista.setText("Buscar");
        btnBuscarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarListaActionPerformed(evt);
            }
        });

        jLabel1.setText(" Digite o código do Contrato para busca:");

        javax.swing.GroupLayout tabListContratosLayout = new javax.swing.GroupLayout(tabListContratos);
        tabListContratos.setLayout(tabListContratosLayout);
        tabListContratosLayout.setHorizontalGroup(
            tabListContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabListContratosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabListContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarLista, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addGroup(tabListContratosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(tabListContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAtualizarLista, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(btnBuscarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(tabListContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );
        tabListContratosLayout.setVerticalGroup(
            tabListContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabListContratosLayout.createSequentialGroup()
                .addContainerGap(466, Short.MAX_VALUE)
                .addGroup(tabListContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtualizarLista, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8)
                .addGroup(tabListContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarLista)
                    .addComponent(txtBuscarLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(tabListContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabListContratosLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 74, Short.MAX_VALUE)))
        );

        tabContratos.addTab("Lista de Contratos", tabListContratos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContratos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContratos)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        
        instanciaContratos = false;
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnSimularValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularValorActionPerformed
        
        ContratoDAO dao = new ContratoDAO();
        int dias = Integer.parseInt(txtDias.getText());
        LocalDate data = LocalDate.now();
        
        if (!txtCodContrato.getText().isEmpty()) {
            
            for (Contrato aluguel : dao.searchIntoDB(txtCodContrato.getText())) {
                
                data = LocalDate.parse(aluguel.getDataFimContrato());
                
            }
            
        }
        
        if (cmbTipo.getSelectedItem() == "Selecione:") {

            txtDesconto.setText(null);
            lblValorDesconto.setText(" Valor com Desconto:");

        } else if (cmbTipo.getSelectedItem().equals("Aplicativo") && !txtDias.getText().isEmpty() && !cmbModelo.getSelectedItem().equals("Selecione:")) {

            ContratoAPP aluguel = new ContratoAPP();
            aluguel.setTipoContrato(cmbTipo.getSelectedItem().toString());
            aluguel.setQtdDiasContrato(txtDias.getText());
            txtValor.setText(aluguel.valorContrato(cmbModelo.getSelectedItem().toString()));
            txtDesconto.setText(aluguel.desconto(Double.parseDouble(txtValor.getText())));
            txtDataFim.setText(data.plusDays(dias).toString());
            btnContrato.setEnabled(true);
            

        } else if (cmbTipo.getSelectedItem().equals("Pessoa Física") && !txtDias.getText().isEmpty() && !cmbModelo.getSelectedItem().equals("Selecione:")) {

            Contrato aluguel = new Contrato();
            aluguel.setTipoContrato(cmbTipo.getSelectedItem().toString());
            aluguel.setQtdDiasContrato(txtDias.getText());
            txtValor.setText(aluguel.valorContrato(cmbModelo.getSelectedItem().toString()));
            txtDesconto.setText(aluguel.desconto(Double.parseDouble(txtValor.getText())));
            txtDataFim.setText(data.plusDays(dias).toString());
            btnContrato.setEnabled(true);
            
        } else if (cmbTipo.getSelectedItem().equals("Pessoa Júridica") && !txtDias.getText().isEmpty() && !cmbModelo.getSelectedItem().equals("Selecione:")) {

            ContratoPJ aluguel = new ContratoPJ();
            aluguel.setTipoContrato(cmbTipo.getSelectedItem().toString());
            aluguel.setQtdDiasContrato(txtDias.getText());
            txtValor.setText(aluguel.valorContrato(cmbModelo.getSelectedItem().toString()));
            txtDesconto.setText(aluguel.desconto(Double.parseDouble(txtValor.getText())));
            txtDataFim.setText(data.plusDays(dias).toString());
            btnContrato.setEnabled(true);

        }
        
    }//GEN-LAST:event_btnSimularValorActionPerformed

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged

        if (cmbTipo.getSelectedItem().equals("Selecione:")) {

            txtDesconto.setText(null);
            lblValorDesconto.setText(" Valor com Desconto:");

        } else if (cmbTipo.getSelectedItem().equals("Aplicativo")) {

            lblValorDesconto.setText(" Valor com 15% de Desconto:");
            lblCPF.setText(" CPF ou CNPJ:");

        } else if (cmbTipo.getSelectedItem().equals("Pessoa Física")) {

            lblValorDesconto.setText(" Valor com 5% de Desconto:");
            lblCPF.setText(" CPF do cliente:");

        } else if (cmbTipo.getSelectedItem().equals("Pessoa Júridica")) {

            lblValorDesconto.setText(" Valor com 10% de Desconto:");
            lblCPF.setText(" CNPJ da empresa:");

        }

    }//GEN-LAST:event_cmbTipoItemStateChanged

    private void cmbModeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbModeloItemStateChanged

        if (cmbModelo.getSelectedItem().equals("Selecione:")) {

            lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oie_401942oYTgxgbD.png")));

        } else if (cmbModelo.getSelectedItem().equals("Palio")) {

            lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oie_transparent.png")));

        } else if (cmbModelo.getSelectedItem().equals("Sandero")) {

            lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oie_3l5CglDkS0i8.png")));

        } else if (cmbModelo.getSelectedItem().equals("Uno")) {

            lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oie_rW2hF85Ww0Og.png")));

        } else if (cmbModelo.getSelectedItem().equals("Argo")) {

            lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oie_transparent (1).png")));

        } else if (cmbModelo.getSelectedItem().equals("Onix")) {

            lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oie_19ytcHrrWbLX.png")));

        } else if (cmbModelo.getSelectedItem().equals("Virtus")) {

            lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oie_vW4d9KAg1hBQ.png")));

        } else if (cmbModelo.getSelectedItem().equals("Gol")) {

            lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oie_1FTFRgOTVAMe.png")));

        } else if (cmbModelo.getSelectedItem().equals("Fluence")) {

            lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fluence.png")));

        } else if (cmbModelo.getSelectedItem().equals("Captur")) {

            lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oie_crGBzVLUhnyU.png")));

        }

    }//GEN-LAST:event_cmbModeloItemStateChanged

    private void txtCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            ClienteDAO dao = new ClienteDAO();

            for (Cliente c : dao.searchIntoDB(txtCPF.getText())) {

                txtNome.setText(c.getNomeCli());

            }

        }

    }//GEN-LAST:event_txtCPFKeyPressed

    private void btnSelecionarVeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarVeiActionPerformed
        
        ContratoDAO dao = new ContratoDAO();
        
        for (Veiculo vei : dao.returnPlaca(cmbMotorizacao.getSelectedItem().toString(), cmbModelo.getSelectedItem().toString())) {
            
            txtPlaca.setText(vei.getPlaca());
            
        }
        
    }//GEN-LAST:event_btnSelecionarVeiActionPerformed

    private void btnContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratoActionPerformed
        
        ContratoDAO dao = new ContratoDAO();
        boolean check = false;
        
        if (cmbTipo.getSelectedItem().equals("Pessoa Física")) {
            
            Contrato pf = new Contrato();
        
            pf.setCPFouCNPJCli(txtCPF.getText());
            pf.setTipoContrato(cmbTipo.getSelectedItem().toString());
            pf.setQtdDiasContrato(txtDias.getText());
            pf.setPlacaVei(txtPlaca.getText());
            pf.setValor_contrato(txtDesconto.getText());
            pf.setDataFimContrato(txtDataFim.getText());
            
            check = dao.insertIntoDBPF(pf);
            
            txtCodContrato.setText(Integer.toString(pf.getCodContrato()));
            
        } else if (cmbTipo.getSelectedItem().equals("Aplicativo")) {
            
            ContratoAPP app = new ContratoAPP();
        
            app.setCPFouCNPJCli(txtCPF.getText());
            app.setTipoContrato(cmbTipo.getSelectedItem().toString());
            app.setQtdDiasContrato(txtDias.getText());
            app.setPlacaVei(txtPlaca.getText());
            app.setValor_contrato(txtDesconto.getText());
            app.setDataFimContrato(txtDataFim.getText());
            
            check = dao.insertIntoDBAPP(app);
            
            txtCodContrato.setText(Integer.toString(app.getCodContrato()));
            txtDataFim.setText(app.getDataFimContrato());
            
        } else if (cmbTipo.getSelectedItem().equals("Pessoa Júridica")) {
            
            ContratoPJ pj = new ContratoPJ();
        
            pj.setCPFouCNPJCli(txtCPF.getText());
            pj.setTipoContrato(cmbTipo.getSelectedItem().toString());
            pj.setQtdDiasContrato(txtDias.getText());
            pj.setPlacaVei(txtPlaca.getText());
            pj.setValor_contrato(txtDesconto.getText());
            pj.setDataFimContrato(txtDataFim.getText());
            
            check = dao.insertIntoDBPJ(pj);
            
            txtCodContrato.setText(Integer.toString(pj.getCodContrato()));
            txtDataFim.setText(pj.getDataFimContrato());
            
        }
        
        if (check ==  true) {
            
            JOptionPane.showMessageDialog(null, "Contrato realizado com sucesso!");
                    
        }
        
        
    }//GEN-LAST:event_btnContratoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAtualizarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarContratoActionPerformed
        
        ContratoDAO dao = new ContratoDAO();
        boolean check = false;
        
        if (cmbTipo.getSelectedItem().equals("Pessoa Física")) {
            
            Contrato pf = new Contrato();
            
            pf.setCodContrato(Integer.parseInt(txtCodContrato.getText()));
            pf.setCPFouCNPJCli(txtCPF.getText());
            pf.setTipoContrato(cmbTipo.getSelectedItem().toString());
            pf.setQtdDiasContrato(txtDias.getText());
            pf.setPlacaVei(txtPlaca.getText());
            pf.setDataFimContrato(txtDataFim.getText());
            pf.setValor_contrato(txtDesconto.getText());
            
            check = dao.alterIntoDBPF(pf);
            
            txtCodContrato.setText(Integer.toString(pf.getCodContrato()));
            
        } else if (cmbTipo.getSelectedItem().equals("Aplicativo")) {
            
            ContratoAPP app = new ContratoAPP();
            
            app.setCodContrato(Integer.parseInt(txtCodContrato.getText()));
            app.setCPFouCNPJCli(txtCPF.getText());
            app.setTipoContrato(cmbTipo.getSelectedItem().toString());
            app.setQtdDiasContrato(txtDias.getText());
            app.setPlacaVei(txtPlaca.getText());
            app.setDataFimContrato(txtDataFim.getText());
            app.setValor_contrato(txtDesconto.getText());
            
            check = dao.alterIntoDBAPP(app);
            
            txtCodContrato.setText(Integer.toString(app.getCodContrato()));
            
        } else if (cmbTipo.getSelectedItem().equals("Pessoa Júridica")) {
            
            ContratoPJ pj = new ContratoPJ();
            
            pj.setCodContrato(Integer.parseInt(txtCodContrato.getText()));
            pj.setCPFouCNPJCli(txtCPF.getText());
            pj.setTipoContrato(cmbTipo.getSelectedItem().toString());
            pj.setQtdDiasContrato(txtDias.getText());
            pj.setPlacaVei(txtPlaca.getText());
            pj.setDataFimContrato(txtDataFim.getText());
            pj.setValor_contrato(txtDesconto.getText());
            
            check = dao.alterIntoDBPJ(pj);
            
            txtCodContrato.setText(Integer.toString(pj.getCodContrato()));
            
        }
        
        if (check == true) {
            
            JOptionPane.showMessageDialog(null, "Contrato atualizado com sucesso!");
                    
        }
        
    }//GEN-LAST:event_btnAtualizarContratoActionPerformed

    private void btnBuscarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarContratoActionPerformed
        
        String cod = JOptionPane.showInputDialog("Digite o CÓDIGO DE CONTRATO que deseja buscar: ");

        recebeBuscaAluguel(cod, 0);

        if (!txtCodContrato.getText().isEmpty()) {

            btnAtualizarContrato.setEnabled(true);
            btnContrato.setEnabled(false);
            txtCodContrato.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_btnBuscarContratoActionPerformed

    private void btnAtualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarListaActionPerformed
        
        readListaAlu();
        
    }//GEN-LAST:event_btnAtualizarListaActionPerformed

    private void btnBuscarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarListaActionPerformed
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < modelo.getRowCount(); i++) {

            if (txtBuscarLista.getText().equals(modelo.getValueAt(i, 0).toString())) {

                jTable1.setRowSelectionInterval(i, i);

            }

        }
        
    }//GEN-LAST:event_btnBuscarListaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        String line = modelo.getValueAt(jTable1.getSelectedRow(), 0).toString();

        if (evt.getClickCount() == 2) {
            
            Object[] options = {"Aba: Atualizar Contrato", "Aba: Revogar Contrato"};
            int choice = JOptionPane.showOptionDialog(null, "Para qual aba você deseja ir?", "Escolha!", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, null);

            if (choice == 0) {
                
                recebeBuscaAluguel(line, 0);
                tabContratos.setSelectedIndex(0);
                btnAtualizarContrato.setEnabled(true);
                btnContrato.setEnabled(false);

            } else {
                
                recebeBuscaAluguel(line, 1);
                tabContratos.setSelectedIndex(1);
                btnRevogar.setEnabled(true);

            }
            

        } else if (evt.getClickCount() == 1) {

            txtBuscarLista.setText(line);

        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnRevogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevogarActionPerformed
        
        Contrato aluguel = new Contrato();
        ContratoDAO dao = new ContratoDAO();
        
        aluguel.setCodContrato(Integer.parseInt(txtCodRev.getText()));
        aluguel.setPlacaVei(txtPlacaRev.getText());
        
        if (dao.deleteFromDB(aluguel, Integer.parseInt(txtKMNovaRev.getText()), cmbAvariadoRev.getSelectedItem().toString())) {
            
            JOptionPane.showMessageDialog(null, "Contrato revogado com sucesso!");
            limparCampos(1);
            
        }
        
    }//GEN-LAST:event_btnRevogarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        limparCampos(0);
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnBuscarRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRevActionPerformed
        
        String cod = JOptionPane.showInputDialog("Digite o CÓDIGO DE CONTRATO que deseja buscar: ");

        recebeBuscaAluguel(cod, 1);
        btnRevogar.setEnabled(true);

        if (!txtCodContrato.getText().isEmpty()) {

            btnRevogar.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_btnBuscarRevActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarContrato;
    private javax.swing.JButton btnAtualizarLista;
    private javax.swing.JButton btnBuscarContrato;
    private javax.swing.JButton btnBuscarLista;
    private javax.swing.JButton btnBuscarRev;
    private javax.swing.JButton btnContrato;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRevogar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSelecionarVei;
    private javax.swing.JButton btnSimularValor;
    private javax.swing.JComboBox<String> cmbAvariadoRev;
    private javax.swing.JComboBox<String> cmbModelo;
    private javax.swing.JComboBox<String> cmbMotorizacao;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAvariadoRev;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPFRev;
    private javax.swing.JLabel lblCodContrato;
    private javax.swing.JLabel lblCodRev;
    private javax.swing.JLabel lblContrato;
    private javax.swing.JLabel lblDataFim;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblKMAntigaRev;
    private javax.swing.JLabel lblKMNova;
    private javax.swing.JLabel lblMotorizacao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeRev;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPlacaRev;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblValorDesconto;
    private javax.swing.JLabel lblVeiculo;
    private javax.swing.JPanel tabContrato;
    private javax.swing.JTabbedPane tabContratos;
    private javax.swing.JPanel tabListContratos;
    private javax.swing.JPanel tabRevogarContrato;
    private javax.swing.JTextField txtBuscarLista;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCPFRev;
    private javax.swing.JTextField txtCodContrato;
    private javax.swing.JTextField txtCodRev;
    private javax.swing.JTextField txtDataFim;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtKMNovaRev;
    private javax.swing.JTextField txtKMVelhaRev;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeRev;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPlacaRev;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    public void setPosicao() {

        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);

    }
    
        public void readListaAlu() {

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        ContratoDAO dao = new ContratoDAO();

        for (Contrato aluguel : dao.listIntoDB()) {

            modelo.addRow(new Object[]{
                aluguel.getCodContrato(),
                aluguel.getPlacaVei(),
                aluguel.getCPFouCNPJCli(),
                aluguel.getDataFimContrato()});

        }

    }
    
    public void recebeBuscaAluguel(String cod, int escolha) {

        ContratoDAO dao = new ContratoDAO();
        ClienteDAO daoCli = new ClienteDAO();
        VeiculoDAO daoVei = new VeiculoDAO(); 
        String CPF = null;
        String Placa = null;
        
        for (Contrato aluguel : dao.searchIntoDB(cod)) {
            
            if (escolha == 0) {
            
                txtCodContrato.setText(Integer.toString(aluguel.getCodContrato()));
                txtCPF.setText(aluguel.getCPFouCNPJCli());
                cmbTipo.setSelectedItem(aluguel.getTipoContrato());
                txtPlaca.setText(aluguel.getPlacaVei());
                txtDataFim.setText(aluguel.getDataFimContrato());
                txtValor.setText(aluguel.getValor_contrato());
                CPF = txtCPF.getText();
                Placa = txtPlaca.getText();
            
            } else if (escolha == 1) {
                
                txtCodRev.setText(Integer.toString(aluguel.getCodContrato()));
                txtCPFRev.setText(aluguel.getCPFouCNPJCli());
                txtPlacaRev.setText(aluguel.getPlacaVei());
                CPF = txtCPFRev.getText();
                Placa = txtPlacaRev.getText();
                
            }

        }
        
        for (Cliente c : daoCli.searchIntoDB(CPF)) {
            
            if (escolha == 0) {
                
                txtNome.setText(c.getNomeCli());
                
            } else if (escolha == 1) {
                
                txtNomeRev.setText(c.getNomeCli());
                
            }

        }
        
        for (VeiculoUsado vei : daoVei.searchIntoDB(Placa)) {
            
            if (escolha == 0) {
                
                cmbModelo.setSelectedItem(vei.getModelo());
                cmbMotorizacao.setSelectedItem(vei.getMotorizacao());
                
            } else if (escolha == 1) {
                
                txtKMVelhaRev.setText(Long.toString(vei.getQuilometragem()));
                cmbAvariadoRev.setSelectedItem(vei.getAvariado());
                
            }
            
        }
        
    }
    
    public void limparCampos(int tab) {
        
        if (tab == 0) {
            
            txtCodContrato.setText(null);
            txtCPF.setText(null);
            cmbTipo.setSelectedItem("Selecione:");
            txtNome.setText(null);
            txtDias.setText(null);
            cmbModelo.setSelectedItem("Selecione:");
            cmbMotorizacao.setSelectedItem("Selecione:");
            txtPlaca.setText(null);
            txtDataFim.setText(null);
            txtValor.setText(null);
            txtDesconto.setText(null);
            btnAtualizarContrato.setEnabled(false);
            btnContrato.setEnabled(false);
            
        }
        
        else {
            
            txtCodRev.setText(null);
            txtNomeRev.setText(null);
            txtCPFRev.setText(null);
            txtPlacaRev.setText(null);
            txtKMVelhaRev.setText(null);
            txtKMNovaRev.setText(null);
            cmbAvariadoRev.setSelectedItem("Selecione:");
            btnRevogar.setEnabled(false);
            
        }
        
    }
    
}
