/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static View.aluguelForm.instanciaContratos;
import javax.swing.JOptionPane;
import static View.cadCliForm.instanciaCadCli;
import static View.veiculosForm.instanciaVeiculo;
import javax.swing.JDesktopPane;

/**
 *
 * @author l_dsb
 */
public class Principal extends javax.swing.JFrame {

    
    public Principal() {
        initComponents();
        setExtendedState(NORMAL);
    }
    
    //public static boolean block = false;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        internalProcedimentos = new javax.swing.JInternalFrame();
        btnAddCar = new javax.swing.JButton();
        btnAluguel = new javax.swing.JButton();
        btnCadCli = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        admMenu = new javax.swing.JMenu();
        cadUsuMenuItem = new javax.swing.JMenuItem();
        alterUsuMenuItem = new javax.swing.JMenuItem();
        suporteMenu = new javax.swing.JMenu();
        chamarSuportetMenuItem = new javax.swing.JMenuItem();
        CentralMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("AluCar");
        setMinimumSize(new java.awt.Dimension(800, 700));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        desktopPane.setBackground(java.awt.SystemColor.control);
        desktopPane.setName(""); // NOI18N

        internalProcedimentos.setTitle("Procedimentos");
        internalProcedimentos.setFocusTraversalPolicyProvider(true);
        internalProcedimentos.setName(""); // NOI18N
        internalProcedimentos.setVisible(true);

        btnAddCar.setIcon(new javax.swing.ImageIcon("C:\\Users\\l_dsb\\OneDrive\\Documentos\\NetBeansProjects\\Alucar\\Images\\if_car_add_35817.png")); // NOI18N
        btnAddCar.setText("VEÍCULOS");
        btnAddCar.setToolTipText("");
        btnAddCar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddCar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAddCar.setPreferredSize(new java.awt.Dimension(70, 20));
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });

        btnAluguel.setIcon(new javax.swing.ImageIcon("C:\\Users\\l_dsb\\OneDrive\\Documentos\\NetBeansProjects\\Alucar\\Images\\if_3_3319636.png")); // NOI18N
        btnAluguel.setText("CONTRATOS");
        btnAluguel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAluguel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAluguelActionPerformed(evt);
            }
        });

        btnCadCli.setIcon(new javax.swing.ImageIcon("C:\\Users\\l_dsb\\OneDrive\\Documentos\\NetBeansProjects\\Alucar\\Images\\if_LinkedIn_UI-08_2335587.png")); // NOI18N
        btnCadCli.setText("CLIENTES");
        btnCadCli.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadCli.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCliActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\l_dsb\\OneDrive\\Documentos\\NetBeansProjects\\Alucar\\Images\\Close_Box_Red.png")); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout internalProcedimentosLayout = new javax.swing.GroupLayout(internalProcedimentos.getContentPane());
        internalProcedimentos.getContentPane().setLayout(internalProcedimentosLayout);
        internalProcedimentosLayout.setHorizontalGroup(
            internalProcedimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalProcedimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(internalProcedimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAluguel, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnCadCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        internalProcedimentosLayout.setVerticalGroup(
            internalProcedimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalProcedimentosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        desktopPane.add(internalProcedimentos);
        internalProcedimentos.setBounds(20, 20, 190, 280);

        admMenu.setText("Administrador");

        cadUsuMenuItem.setText("Cadastrar Usuario");
        admMenu.add(cadUsuMenuItem);

        alterUsuMenuItem.setText("Alterar Usuario");
        admMenu.add(alterUsuMenuItem);

        menuBar.add(admMenu);

        suporteMenu.setMnemonic('s');
        suporteMenu.setText("Suporte");

        chamarSuportetMenuItem.setText("Chamar Suporte");
        suporteMenu.add(chamarSuportetMenuItem);

        CentralMenuItem.setText("Ligar para Central");
        suporteMenu.add(CentralMenuItem);

        menuBar.add(suporteMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarActionPerformed
        
        if (instanciaVeiculo == false) {
            
            veiculosForm form = new veiculosForm();
            desktopPane.add(form);
            form.setPosicao();
            form.setVisible(true);
            instanciaVeiculo = true;
            
        } 
        
    }//GEN-LAST:event_btnAddCarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        Object[] options = {"Ficar", "Sair"};
        int choice = JOptionPane.showOptionDialog(null, "Você realmente deseja sair?", "AluCar", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        
        if (choice == 1) {
            
            System.exit(0);
            
        }
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCliActionPerformed
        
        if (instanciaCadCli == false) {
            
            cadCliForm form = new cadCliForm();
            desktopPane.add(form);
            form.setPosicao();
            form.setVisible(true);
            instanciaCadCli = true;
            
        } 
        
    }//GEN-LAST:event_btnCadCliActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
       
        /*if (evt.getNewState() != 7) {
  
            setExtendedState(MAXIMIZED_BOTH);

        }*/
        
    }//GEN-LAST:event_formWindowStateChanged

    private void btnAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAluguelActionPerformed
        
        if (instanciaContratos == false) {
            
            aluguelForm form = new aluguelForm();
            desktopPane.add(form);
            form.setPosicao();
            form.setVisible(true);
            instanciaContratos = true;
            
        } 
        
    }//GEN-LAST:event_btnAluguelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CentralMenuItem;
    private javax.swing.JMenu admMenu;
    private javax.swing.JMenuItem alterUsuMenuItem;
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnAluguel;
    private javax.swing.JButton btnCadCli;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuItem cadUsuMenuItem;
    private javax.swing.JMenuItem chamarSuportetMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JInternalFrame internalProcedimentos;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu suporteMenu;
    // End of variables declaration//GEN-END:variables

}
